name: Deploy to Fly

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: latest

      - name: Login to Fly
        run: flyctl auth login --access-token ${{ secrets.FLY_ACCESS_TOKEN }}

      - name: Set environment variables
        uses: superfly/flyctl-actions/flyctl-secrets@v1
        with:
          app-name: graphql-project
          secrets: |
            NEXT_PUBLIC_SHOPIFY_STOREFRONT_NAME=${{ secrets.SHOPIFY_STOREFRONT_NAME }}
            NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN=${{ secrets.SHOPIFY_STOREFRONT_ACCESS_TOKEN }}
            NEXT_PUBLIC_DEMO_MODE=false

      - name: Deploy app to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
